wandb_version: 1

ac:
  value: relu
batch_size:
  value: 16
epochs:
  value: 5
hidden_layer_size:
  value: 128
hidden_layers:
  value: 5
init_strategy:
  value: xavier
learning_rate:
  value: 0.001
optimiser:
  value: nag
weight_decay:
  value: 0
