wandb_version: 1

ac:
  value: sig
batch_size:
  value: 32
epochs:
  value: 5
hidden_layer_size:
  value: 128
hidden_layers:
  value: 3
init_strategy:
  value: xavier
learning_rate:
  value: 0.001
optimiser:
  value: nadam
weight_decay:
  value: 0.0005
