wandb_version: 1

ac:
  value: relu
batch_size:
  value: 16
epochs:
  value: 5
hidden_layer_size:
  value: 64
hidden_layers:
  value: 4
init_strategy:
  value: xavier
learning_rate:
  value: 0.0001
optimiser:
  value: sgd
weight_decay:
  value: 0.0005
