wandb_version: 1

ac:
  value: tanh
batch_size:
  value: 64
epochs:
  value: 10
hidden_layer_size:
  value: 32
hidden_layers:
  value: 5
init_strategy:
  value: xavier
learning_rate:
  value: 0.001
optimiser:
  value: adam
weight_decay:
  value: 0
