wandb_version: 1

ac:
  value: tanh
batch_size:
  value: 32
epochs:
  value: 5
hidden_layer_size:
  value: 64
hidden_layers:
  value: 3
init_strategy:
  value: xavier
learning_rate:
  value: 0.001
optimiser:
  value: sgd
weight_decay:
  value: 0.5
